name: popsimwraptor
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip>=24
  - numpy=1.24.*
  - pandas>=2.2,<2.3
  - tqdm>=4.66
  - bcftools>=1.18
  - htslib>=1.18
  - slim=4.1
  - msprime>=1.2,<1.4
  - pyslim>=1.0.4,<1.2
  - tskit>=0.5.6,<0.6
  - demes=0.2.3
  - openjdk=17
  - git
  - make
  - gcc_linux-64
  - gxx_linux-64
  - pip:
      - stdpopsim==0.3.0
      - -e .
